# Generated by Django 4.1.3 on 2022-12-02 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('04ead423-7974-4fb2-b862-a8b16292f756'), primary_key=True, serialize=False)),
                ('assigned', models.BooleanField(default=False)),
                ('img', models.FileField(upload_to='img/', verbose_name='img')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('file_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='url')),
            ],
        ),
    ]
