# Generated by Django 4.1.3 on 2023-01-18 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f284da2-957c-44b1-b715-d8abfcbe8360'), primary_key=True, serialize=False),
        ),
    ]
