# Generated by Django 4.1.3 on 2023-01-19 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0005_alter_examplemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7b8863b-7ab2-44b2-903c-84317f09a74d'), primary_key=True, serialize=False),
        ),
    ]
