# Generated by Django 4.1.3 on 2023-01-24 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0006_alter_examplemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ecf63ab-459d-44f2-ad1a-e91690fb0a52'), primary_key=True, serialize=False),
        ),
    ]
