# Generated by Django 4.1.3 on 2023-02-08 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0008_alter_examplemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cce81bd-5d14-4105-adb7-d647fba7064c'), primary_key=True, serialize=False),
        ),
    ]
