# Generated by Django 4.1.3 on 2023-02-16 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0011_alter_examplemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05990f43-fc63-4b84-95cb-ec06ab7fd8e6'), primary_key=True, serialize=False),
        ),
    ]
