apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: postgresql-db-disk-pv
  accessModes:
    - ReadWriteOnce

  storageClassName: standard
  resources:
    requests: 
      storage: 1Gi
